### ISSUE TITLE
dotnet6 support?

### ISSUE THREAD

**Issue by ymccready** [blackducksoftware/nuget-dotnet5-inspector#1]
Hello,
Sorry this might not be the exactly correct repo to open this issue, but it seems the correct repo doesn't exist yet. :)

Is there a plan to have an inspector that supports dotnet 6?
For projects that use dotnet 6, we have to still install dotnet 5 for BlackDuck Detect to scan. 

Thanks,

**Comment by timmkrause** [comment]
![](https://media3.giphy.com/media/l4FGxSgCJSLCg6mVa/giphy.gif?cid=ecf05e47vcrr4669fsa5caweoyr6x287l0u516qj5isdhqhm&rid=giphy.gif&ct=g)

**Comment by timmkrause** [comment]
![](https://media1.giphy.com/media/l4FGxSgCJSLCg6mVa/giphy.gif?cid=ecf05e47r52rtpqmo8lpcmggo661z4ai71evvt9c0cf7kkb6&rid=giphy.gif&ct=g)

**Comment by ymccready** [comment]
So apparently this is resolved in a different repo here that seems to target DotNet 6:
https://github.com/blackducksoftware/detect-nuget-inspector

**Comment by timmkrause** [comment]
Nevertheless. The communication can be... improved...
